include:
   - project: nse/ci
     file:
        - /ci/lib/tox-bb5.yml
        - /ci/jobs/check-version.yml
        - /ci/jobs/check-packaging.yml
        - /ci/jobs/lint.yml
        - /ci/jobs/docs.yml
        - /ci/jobs/build-package.yml
        - /ci/jobs/publish-package.yml
        - /ci/jobs/publish-docs.yml
        - /ci/jobs/tag.yml
   - project: neuromath/ci
     file:
        - /ci/jobs/auto-release.yml
        - /ci/jobs/check-merge-request-title.yml
        - /ci/lib/pytest-template.yml
        - /ci/jobs/py38.yml
        - /ci/jobs/py39.yml
        - /ci/jobs/py310.yml
        - /ci/jobs/min_versions.yml
        - /ci/jobs/coverage.yml

.tox-template:
  variables:
    EXTRA_MODULES:
      archive/2024-01:py-mpi4py
    bb5_cpus_per_task: 8
    bb5_memory: 6G
